#!/bin/bash

cd files

for i in {a..z}
        do
                mv ${i}*.txt ~/assignment_week8/${i}
        done
for i in {A..Z}
        do
                mv ${i}*.txt ~/assignment_week8/${i}
        done
